//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRepairing.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public string C_FirstName { get; set; }
        public string C_SecondName { get; set; }
        public string C_LastName { get; set; }
        public string C_PhoneNumber { get; set; }
        public System.DateTime DateOfRequest { get; set; }
        public bool IsAccepted { get; set; }
        public int StateID { get; set; }
        public int DeviceID { get; set; }
        public Nullable<decimal> RepairCost { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual State State { get; set; }
    }
}
